# Generated by Django 5.1 on 2025-11-11 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_simplify_customerwarranty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issuecomment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="issuerelation",
            name="relation_type",
            field=models.CharField(
                choices=[("relates", "相關"), ("duplicates", "重複")], max_length=20
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name="issue",
                    index=models.Index(
                        fields=["status", "-updated_at"], name="issues_status_171ab4_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="issue",
                    index=models.Index(
                        fields=["project", "created_at"], name="issues_project_0b4a6f_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="issue",
                    index=models.Index(
                        fields=["customer", "created_at"], name="issues_custome_a2aa08_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="issue",
                    index=models.Index(
                        fields=["assignee", "status"], name="issues_assigne_2da979_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="issuecomment",
                    index=models.Index(
                        fields=["issue", "created_at"],
                        name="issue_comme_issue_i_937053_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="issuestatushistory",
                    index=models.Index(
                        fields=["issue", "-changed_at"],
                        name="issue_statu_issue_i_b51399_idx",
                    ),
                ),
            ],
        ),
    ]
